### ISSUE TITLE
New UPMPublishing workflow not working.

### ISSUE THREAD

**Issue by pizzaandpineapples** [Studio-23-xyz/com.studio23.ss2.audiosystem.fmod#5]
- For now the package is using the old workflow so that updates can be published to OpenUPM.
- SelfHosted-Publish job is failing

![image](https://github.com/Studio-23-xyz/com.studio23.ss2.audiosystem.fmod/assets/41065855/8f01ab88-bb79-46ff-ad68-6165595cbdf5)

**Comment by Warhammer4000** [comment]
False alert. it works as intended
